name: Check JavaScript for conformance with Prettier

on:
  push:
  pull_request:

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
    - name: Install dependencies
      run: yarn
    - name: Run prettier
      run: yarn prettier --check "**/*.{scss,js,jsx,json,md}"